### ISSUE TITLE
Add margins to UI elements

### ISSUE THREAD

**Issue by bpezer** [tengel/GeologicalTimescale#4]
The app would benefit from some layout tweaks, in particular adding margins to the dialogs and main activity. Currently, the situation is like this:

![geo](https://user-images.githubusercontent.com/47884610/97246466-b1146280-17fd-11eb-8de6-7e2a4fb34bb1.jpg)
<br>
<br>
<br>
Something like this would be an improvement:

![geofix](https://user-images.githubusercontent.com/47884610/97246538-e02ad400-17fd-11eb-8f03-5532e89fc869.jpg)

**Comment by tengel** [comment]
There is a new info dialog in 0.6.0.
